version: "3.9"

services:
  postgres:
    image: postgres
    volumes:
    - ./database:/var/lib/postgresql/data
    ports:
    - 5432:5432
    environment:
      - POSTGRES_DB=portfolio
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=secret