version: '3.5'


service:
    postgres:
        image: postgres:15.1
        volumes:
            - ./database:/var/lib/postgresql/data
        ports:
            -5432:5432
        environment:
            - POSTGRES_DB=todo
            - POSTGRES_USER=developer
            - POSTGRES_PASSWORD=secret



